#https端口(http端口在 src/main/java/work/yj1211/live/config/TomcatConfig.java里配置)
server:
  port: 8014

#mysql配置
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/mixlive?serverTimezone=UTC&allowMultiQueries=true&characterEncoding=utf-8&useSSL=false&allowPublicKeyRetrieval=True&allowMultiQueries=true
    username: root
    password: 5201314
path:
  #网页端TV源列表文件路径(现在不用了)
  m3uPath: m3u8.txt
  #app版本更新信息文件路径
  updateFilePath: update.txt

ali:
  mail:
    accessKeyId: 123
    accessKeySecret: 123